language: node_js
node_js:
  - 'lts/*'
  - 'node'
sudo: false

after_success:
  - npm run coverage

deploy:
  provider: npm
  email: "hugo.armstrong@gmail.com"
  api_key: $api_key
  on:
    tags: true
